[package]
name = "learning"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
rand="0.8.5"
tensor = { path = "../tensor" }
optimization = { path = "../optimization" }
statistics = { path = "../statistics" }
